package com.loottable.broadcasts.detection;

import java.util.Set;

import net.runelite.api.gameval.ItemID;

public class NotableDropItems
{
	private static final Set<Integer> NOTABLE_ITEM_IDS = Set.of(
		// General items
		ItemID.TWISTED_BOW,
		ItemID.SCYTHE_OF_VITUR_UNCHARGED,
		ItemID.TUMEKENS_SHADOW_UNCHARGED,
		ItemID.ELYSIAN_SIGIL,
		ItemID.ARCANE_SIGIL,
		ItemID.SPECTRAL_SIGIL,
		ItemID.VOLATILE_ORB,
		ItemID.ELDRITCH_ORB,
		ItemID.HARMONISED_ORB,
		ItemID.INQUISITORS_MACE,
		ItemID.INQUISITORS_SKIRT,
		ItemID.INQUISITORS_BODY,
		ItemID.INQUISITORS_HELM,
		ItemID.OATHPLATE_CHEST,
		ItemID.OATHPLATE_LEGS,
		ItemID.OATHPLATE_HELM,
		ItemID.BROKEN_TORVA_CHEST,
		ItemID.BROKEN_TORVA_LEGS,
		ItemID.BROKEN_TORVA_HELM,
		ItemID.NIHIL_HORN,
		ItemID.ELDER_MAUL,
		ItemID.PRIF_WEAPON_SEED_ENHANCED,
		ItemID.ANCESTRAL_ROBE_TOP,
		ItemID.KODAI_INSIGNIA,
		ItemID.ELDER_VENATOR_FANG,
		ItemID.AVERNIC_TREADS,
		ItemID.BRUT_DRAGON_FULL_HELM,
		ItemID.IMBUED_HEART,
		ItemID.SLAYER_ETERNAL_GEM,
		ItemID.BOTTOMLESS_COMPOST_BUCKET,
		ItemID.DRAGON_HARPOON,
		ItemID.RED_MUTAGEN,
		ItemID.CYAN_MUTAGEN,
		// 3rd Age
		ItemID.TRAIL_RANGER_TORSO,
		ItemID.TRAIL_RANGER_LEGS,
		ItemID.TRAIL_RANGER_COIF,
		ItemID.TRAIL_RANGER_VAMBRACES,
		ItemID.TRAIL_MAGE_TORSO,
		ItemID.TRAIL_MAGE_LEGS,
		ItemID.TRAIL_MAGE_HAT,
		ItemID.TRAIL_MAGE_AMULET,
		ItemID.TRAIL_SILVER_PLATE_LEGS,
		ItemID.TRAIL_SILVER_PLATE_CHEST,
		ItemID.TRAIL_FIGHTER_HELM,
		ItemID.TRAIL_FIGHTER_SHIELD,
		ItemID.TRAIL_MAGE_WAND,
		ItemID.TRAIL_RANGER_BOW,
		ItemID.TRAIL_FIGHTER_SWORD,
		ItemID.TRAIL_THIRD_CAPE,
		ItemID._3A_AXE,
		ItemID._3A_PICKAXE,
		ItemID.TRAIL_SILVER_PLATE_SKIRT,
		ItemID._3A_DRUIDIC_TOP,
		ItemID._3A_DRUIDIC_BOTTOMS,
		ItemID._3A_DRUIDIC_STAFF,
		ItemID._3A_DRUIDIC_CLOAK,
		ItemID._3A_AXE_2H,
		// Gilded
		ItemID.RUNE_PLATEBODY_GOLDPLATE,
		ItemID.RUNE_PLATELEGS_GOLDPLATE,
		ItemID.RUNE_PLATESKIRT_GOLDPLATE,
		ItemID.RUNE_FULL_HELM_GOLDPLATE,
		ItemID.RUNE_KITESHIELD_GOLDPLATE,
		ItemID.RUNE_SCIMITAR_GOLD,
		ItemID.RUNE_BOOTS_GOLD,
		ItemID.RUNE_MED_HELM_GOLD,
		ItemID.RUNE_CHAINBODY_GOLD,
		ItemID.RUNE_SQ_SHIELD_GOLD,
		ItemID.RUNE_2H_SWORD_GOLD,
		ItemID.RUNE_SPEAR_GOLD,
		ItemID.BRUT_RUNE_SPEAR_GOLD,
		ItemID.TRAIL_GILDED_DHIDE_COIF,
		ItemID.TRAIL_GILDED_DHIDE_VAMBRACES,
		ItemID.TRAIL_GILDED_DHIDE_TOP,
		ItemID.TRAIL_GILDED_DHIDE_CHAPS,
		ItemID.TRAIL_GILDED_PICKAXE,
		ItemID.TRAIL_GILDED_AXE,
		ItemID.TRAIL_GILDED_SPADE
	);

	public boolean isNotableItem(int itemId)
	{
		return NOTABLE_ITEM_IDS.contains(itemId);
	}
}